services:
  - type: web
    name: hrms-backend
    runtime: java
    rootDir: hrms-backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d6iirp7gi27c738ipm90-a/hrms_db_gyb3
      - key: SPRING_DATASOURCE_USERNAME
        value: hrms_db_gyb3_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 0lbvjubPXGaG7fHltQbzfjv6jEbqYQEY
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SERVER_PORT
        value: 8080

  - type: web
    name: hrms-frontend
    runtime: static
    rootDir: hrms-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://hrms-backend.onrender.com